### ISSUE TITLE
Cannot use close_open_position()

### ISSUE THREAD

**Issue by erik47** [ig-python/ig-markets-api-python-library#122]
Hi fellow traders,

I am very new to python and github but really trying to learn, so please bear with me if I seem a little confused.

I have managed to open positions both via IG:s API companion and using the POST method create_open_position(), but can´t seem to close my positions using close_open_position() no matter how I try. I know it is a known issue that the delete requests have not been working in the past, and that one has to:

1. change your DELETE method to POST
2. Add an header with key "_method" and value "DELETE"

( according to https://labs.ig.com/node/36 )

My initial thought was that this was taken care of in the close_open_position() method, but I am not sure even after inspecting the source code. I am getting errors: 

{"errorCode":"validation.mutual-exclusive-value.request"}
{"errorCode":"validation.null-conditional-set-value.request"}

when I run something like:

ig_service.close_open_position(deal_id='DIAAAADV5NXYMAP',
                               direction='BUY',
                               epic="IX.D.DAX.IFMM.IP",
                               expiry= "-",
                               level= "",
                               order_type= "MARKET",
                               quote_id= "",
                               size= "1")

( I also tried using None instead of "" for level and quote_id)

Any help would be greatly appreciated as I have been trying to solve this problem myself for the last 24h without any avail.

**Comment by meadjrm2** [comment]
Hi Erik, I had the same problem for a few weeks.First thing to try is to change the direction to “SELL”.I’m assuming you’re trying to close a “BUY” position.That got it working for me. Kind regardsJohn From: erik47Sent: 05 June 2020 12:06To: ig-python/ig-markets-api-python-libraryCc: SubscribedSubject: [ig-python/ig-markets-api-python-library] Cannot use close_open_position() (#122) Hi fellow traders,I am very new to python and github but really trying to learn, so please bear with me if I seem a little confused.I have managed to open positions both via IG:s API companion and using the POST method create_open_position(), but can´t seem to close my positions using close_open_position() no matter how I try. I know it is a known issue that the delete requests have not been working in the past, and that one has to:change your DELETE method to POSTAdd an header with key "_method" and value "DELETE"( according to https://labs.ig.com/node/36 )My initial thought was that this was taken care of in the close_open_position() method, but I am not sure even after inspecting the source code. I am getting errors:{"errorCode":"validation.mutual-exclusive-value.request"}{"errorCode":"validation.null-conditional-set-value.request"}when I run something like:ig_service.close_open_position(deal_id='DIAAAADV5NXYMAP',direction='BUY',epic="IX.D.DAX.IFMM.IP",expiry= "-",level= "",order_type= "MARKET",quote_id= "",size= "1")( I also tried using None instead of "" for level and quote_id)Any help would be greatly appreciated as I have been trying to solve this problem myself for the last 24h without any avail.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com

**Comment by erik47** [comment]
THANKS!! Finally got it working now with your tip. Except the trade direction, I had to make sure that I left out the epic and expiry completely (i.e. trade is only identified by dealId and not market), and had the empty parameters as None.

The code belowis  what worked for me for someone who might face the same problem:

ig_service.close_open_position(deal_id= "XXXX",
                               direction= "SELL",
                               epic= None,
                               expiry= None,
                               level= None,
                               order_type= "MARKET",
                               quote_id= None,
                               size= "1")
