### ISSUE TITLE
15min candle data

### ISSUE THREAD

**Issue by alhennessey92** [ig-python/ig-markets-api-python-library#199]
Hi
Is there a way to easily stream 15 or 30 min data?
The api docs show only 5min - 1 day and look to miss out the 15 and 30 min candles.
I have tried to stream the data on my application but I don’t receive any data.
Thanks for the help
Al

**Comment by RRMXkun** [comment]
You have to compile the data yourself. Stream the 5 min and only record the high/lows of every 3rd candle for 15 min and every 6th candle for 30 min.

**Comment by RRMXkun** [comment]
Update, I have been looking to use the 15 and 30min charts myself. There is a more flexible way of doing so than I outlined above. The key is to subscribe to CHART_TICK rather than CHART. Well not exactly but this is what the subscription looks like:

```python
Subscription(mode='DISTINCT',
items=['CHART:<EPIC>:TICK'],
fields=['UTM', 'OFR', 'BID']
)
```

Pandas comes with a neat resampling method which can take many common timeframes as argument e.g. 1Min, 5Min, 15Min, 30Min, etc. Using this you can generate candles for any timeframe you want. First we of course load the raw data received from lightstreamer into a panda Dataframe:
```python
tick_dictionary = {}
# Converts UTM value received from LS into a usable timestamp object for Pandas
timestamp_index = pd.Timestamp(int(item_update['values']['UTM']), unit='ms')
# Add newly received row to data dictionary
update = {timestamp_index: {'UTM': float(item_update['values']['UTM']),
                                    'OFR': float(item_update['values']['OFR']),
                                    'BID': float(item_update['values']['BID']),
                                    }
                  }
tick_dictionary.update(update)
# Create panda dataframe from dictionary
df = pd.DataFrame.from_dict(tick_dictionary, orient='index')
```

Now we have a Pandas dataframe we can use the resample method (ohlc = Open High Low Close):

```python
candles_dataframe = df.resample('15Min').ohlc()
```

The output is a dataframe with Open, High, Low, Close columns and of course the timestamp as index. The good thing is, you can generate candles for various timeframes all using the same data - no need to subscribe to multiple streams.
