### ISSUE TITLE
Exception: error.public-api.exceeded-account-historical-data-allowance

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#21]
many queries now return an exception 

```
error.public-api.exceeded-account-historical-data-allowance
```

**Comment by 99epep** [comment]
Isn't it simply due to the 10000 prices per week limitation ?

http://labs.ig.com/faq#limits

When asking at prices through REST API, there is an "allowance" part in the response, containing "remainingAllowance", "totalAllowance" and "allowanceExpiry". Doesn't this exception occur when remainingAllowance == 0 ?

**Comment by femtotrader** [comment]
yes it's... I should found a workaround to test this library without reaching limits

**Comment by bug-or-feature** [comment]
Not an issue - its a known and published limitation of the IG API. Closing
