### ISSUE TITLE
Cannot import name 'munchify'

### ISSUE THREAD

**Issue by ErikHougaard** [ig-python/ig-markets-api-python-library#215]
Hi,

I am trying to run the basic examples in a Jupyter notebook (Python3), but I get this error:

ImportError: cannot import name 'munchify' from 'trading_ig.utils' (/usr/local/lib/python3.7/dist-packages/trading_ig/utils.py)

I tried installing munch via pip, but that made no difference.

Thanks in advance,

Erik

**Comment by ttamg** [comment]
I have the same issue.  

Interestingly, the offending line `from munch import munchify` seems to work fine on my command line too.

**Comment by ttamg** [comment]
I think I found the issue and have it resolved.  

In my project I need to install all the extra packages with `pip install trading_ig pandas tenacity munch` or `poetry add trading_ig pandas tenacity munch`.  Thereafter when spinning up the juptyer notebook fresh and rerunning, the previous error message is removed.

I think the issue is that in the **pyproject.toml** file the dependencies for `pandas`, `tenacity`, and `munch` are labelled as `optional=true`.  I'm sure there are reasons for this, but it does mean that as a user of this package, I need to install those separately.

This is something that could be fixed?

From **pyproject.toml**...
```
[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
requests = "^2.24"
pycryptodome = "^3.9"
requests-cache = "^0.5"
six = "^1.15"

pandas = { version = "^1", optional = true }
munch = { version = "^2.5", optional = true }
tenacity = { version = "^7.0", optional = true }
Sphinx = { version = "^4.0.3", optional = true }
sphinx-rtd-theme = { version = "^0.5.2", optional = true }
```

**Comment by bug-or-feature** [comment]
Thos imports are [optional by design](https://trading-ig.readthedocs.io/en/latest/faq.html#why-is-pandas-an-optional-dependency-in-pyproject-toml)

I have created a new task (#216) to improve the error handling and docs for the optional imports
